---

- name: Install Tenable Nessus on Debian
  hosts: tenableserver
  become: yes
  vars:
    tenable_version: "10.8.3"
    tenable_download_url: "https://www.tenable.com/downloads/api/v2/pages/nessus/files/Nessus-{{ tenable_version }}-debian10_amd64.deb"
  tasks:
    - name: Install ca-certifications NEEDED DO NOT REMOVE
      ansible.builtin.apt:
        name: ca-certificates
        state: present
      when: ansible_os_family == "Debian"

    - name: Download Nessus Package for Debian Server
      ansible.builtin.get_url:
        url: "{{ tenable_download_url }}"
        dest: "/tmp/Nessus.deb"
        mode: '0644'

    - name: Install Nessus on Debian Server
      command: "dpkg -i /tmp/Nessus.deb"

    - name: Start and Enable Nessus
      ansible.builtin.systemd_service:
        name: nessusd
        state: started
        enabled: yes

    - name: Display Nessus Web URL to User
      debug:
        msg: "Access Nessus at http://{{ ansible_default_ipv4.address }}:8834"
