---
# Enable Administrator account and set password
- name: Enable the built-in Administrator account
  win_user:
    name: Administrator
    password: "{{ admin_password }}"
    account_disabled: no
    update_password: always
    state: present

# Ensure the Downloads folder exists
- name: Create Downloads folder for Administrator
  win_file:
    path: "C:\\Users\\Administrator\\Downloads"
    state: directory

# 1. Check if Splunk Forwarder MSI is already downloaded
- name: Check if Splunk Forwarder MSI exists
  win_stat:
    path: "C:\\Users\\Administrator\\Downloads\\{{ splunk_forwarder_package }}"
  register: splunk_installer

# 2. Download Splunk Forwarder if missing
- name: Download Splunk Forwarder for Windows
  win_get_url:
    url: "{{ splunk_forwarder_download_url }}"
    dest: "C:\\Users\\Administrator\\Downloads\\{{ splunk_forwarder_package }}"
  when: not splunk_installer.stat.exists

# 3. Unblock the downloaded MSI
- name: Unblock Splunk MSI File
  win_shell: |
    Unblock-File -Path "C:\\Users\\Administrator\\Downloads\\{{ splunk_forwarder_package }}"
  args:
    executable: powershell.exe
  when: splunk_installer.stat.exists

# 4. Install Splunk Forwarder with deployment and indexer settings
- name: Install Splunk Forwarder with verbose logging
  win_command: >
    msiexec /i "C:\\Users\\Administrator\\Downloads\\{{ splunk_forwarder_package }}"
    AGREETOLICENSE=Yes
    INSTALLDIR="{{ splunk_forwarder_install_dir }}"
    SPLUNKUSERNAME=admin
    SPLUNKPASSWORD=password
    /quiet /norestart /L*v "C:\\splunk_install_log.txt"
  args:
    creates: "{{ splunk_forwarder_install_dir }}\\bin\\splunk.exe"
  register: splunk_install
  become: yes
  become_method: runas
  become_user: Administrator

- name: Show install result
  debug:
    var: splunk_install

- name: Show install result
  debug:
    var: splunk_install
# 5. Check if splunk.exe was installed
- name: Verify Splunk executable exists after install
  win_stat:
    path: "{{ splunk_forwarder_install_dir }}\\bin\\splunk.exe"
  register: splunk_check

- name: Debug Splunk install status
  debug:
    msg: "Splunk Forwarder installed successfully."
  when: splunk_check.stat.exists

# 6. Ensure local config directory exists
- name: Ensure Splunk local configuration directory exists
  win_file:
    path: "{{ splunk_forwarder_install_dir }}\\etc\\system\\local"
    state: directory

# 7. Deploy outputs.conf
- name: Configure outputs.conf for Splunk Forwarder (Windows)
  ansible.windows.win_template:
    src: outputs.conf.j2
    dest: "{{ splunk_forwarder_install_dir }}\\etc\\system\\local\\outputs.conf"

# 8. Deploy inputs.conf
- name: Deploy inputs.conf (Enable Windows Event Logs + File monitoring)
  win_template:
    src: inputs.conf.j2
    dest: "{{ splunk_forwarder_install_dir }}\\etc\\system\\local\\inputs.conf"
  notify: Restart Splunk Forwarder

# 9. Add deployment.conf
- name: Deploy deploymentclient.conf
  win_template:
    src: deploymentclient.conf.j2
    dest: "{{ splunk_forwarder_install_dir }}\\etc\\system\\local\\deploymentclient.conf"

# 10. Start and enable the service
- name: Start and enable Splunk Forwarder
  win_service:
    name: SplunkForwarder
    state: started
    start_mode: auto
  when: splunk_check.stat.exists
