- name: Set domain Administrator password
  ansible.windows.win_user:
    name: Administrator
    password: "{{ domain_admin_password }}"
    update_password: always
    state: present
    account_disabled: no

- name: Enable AutoAdminLogon
  ansible.windows.win_regedit:
    path: 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon'
    name: AutoAdminLogon
    data: "1"
    type: string

- name: Set DefaultUsername
  ansible.windows.win_regedit:
    path: 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon'
    name: DefaultUsername
    data: "Administrator"
    type: string

- name: Set DefaultDomainName
  ansible.windows.win_regedit:
    path: 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon'
    name: DefaultDomainName
    data: "{{ netbios_name }}"
    type: string

- name: Set DefaultPassword
  ansible.windows.win_regedit:
    path: 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon'
    name: DefaultPassword
    data: "{{ domain_admin_password }}"
    type: string

- name: Install OpenSSH Server
  win_command: powershell.exe -Command "Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0"
  register: sshd_install
  changed_when: "'Success' in sshd_install.stdout"

- name: Start and enable SSHD
  ansible.windows.win_service:
    name: sshd
    start_mode: auto
    state: started
