---
- name: Update Debian packages
  hosts: openvas
  become: true
  tasks:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade installed packages
      ansible.builtin.apt:
        upgrade: dist

    - name: Autoremove unnecessary packages
      ansible.builtin.apt:
        autoremove: yes

